export const METRIC_TIPS = {
  trailingPE: "Price-to-Earnings based on trailing 12 months. Lower values can indicate cheaper valuation, but context matters.",
  forwardPE: "Price-to-Earnings based on forward earnings estimates. Lower values suggest less optimism is priced in.",
  pegRatio: "P/E divided by expected earnings growth. Around 1 is often treated as growth-adjusted fair value.",
  priceToBook: "Price relative to book value. More useful for asset-heavy businesses than for software or service firms.",
  priceToSales: "Price relative to revenue. Useful when earnings are weak or volatile.",
  marketCap: "Total market value of the company’s equity.",
  enterpriseValue: "Market cap plus debt minus cash. A cleaner total-value measure than market cap alone.",
  enterpriseToRevenue: "Enterprise value divided by revenue. Measures what the market pays per dollar of sales.",
  enterpriseToEbitda: "Enterprise value divided by EBITDA. Common shorthand for operating valuation.",
  earningsYield: "Inverse of P/E. Higher values mean more earnings per dollar invested.",
  fcfYield: "Free cash flow divided by market cap. Higher values suggest more cash generation relative to price.",
  revenueGrowth: "Year-over-year revenue growth. Positive growth usually indicates business expansion.",
  earningsGrowth: "Year-over-year earnings growth. More volatile than revenue growth, but important for profitability trends.",
  grossMargins: "Gross profit divided by revenue. Shows how efficiently the company produces what it sells.",
  operatingMargins: "Operating income divided by revenue. A cleaner measure of core business profitability.",
  profitMargins: "Net income divided by revenue. Captures bottom-line profitability after all expenses.",
  returnOnEquity: "Net income relative to shareholder equity. Measures how effectively equity capital is used.",
  returnOnAssets: "Net income relative to total assets. Shows how effectively the asset base generates profit.",
  fcfMargin: "Free cash flow divided by revenue. Shows how much revenue turns into spendable cash.",
  debtToEquity: "Debt relative to shareholder equity. Higher values can indicate higher financial risk.",
  currentRatio: "Current assets divided by current liabilities. Helps assess short-term liquidity.",
  quickRatio: "Like current ratio, but excludes inventory. A stricter liquidity test.",
  beta: "Sensitivity to market movements. Above 1 means more volatile than the market.",
  shortPercentOfFloat: "Short interest as a share of tradable float. High values can signal bearish positioning or squeeze risk.",
  impliedMove: "Options-implied expected move into expiry based on the ATM straddle.",
  opportunityScore: "Composite score blending valuation, quality, risk, options posture, and upside gap when available.",
  valuationScore: "Composite score from the available valuation inputs only.",
  qualityScore: "Composite score from the available profitability, growth, and cash-generation inputs only.",
  riskScore: "Composite score from the available leverage, liquidity, volatility, and event-risk inputs only.",
  optionsScore: "Composite score from the available options-implied positioning inputs only.",
  fundamentalsScore: "Composite score from the available raw fundamental fields only.",
  valuationVerdict: "High-level interpretation of the current valuation inputs.",
  qualityVerdict: "High-level interpretation of the current business quality inputs.",
  riskVerdict: "High-level interpretation of the current risk inputs.",
  fairValueRange: "Scenario range based on the valuation methods available for this ticker.",
};
